### ISSUE TITLE
missing systems.csv file causes failure

### ISSUE THREAD

**Issue by therealcmj** [jakehadar/bikeshare-client-python#1]
From const.py:

```
gbfs_systems_csv_remote_url = 'https://raw.githubusercontent.com/NABSA/gbfs/master/systems.csv'
gbfs_systems_csv_local_filepath = os.path.join(package_static_dirpath, 'systems.csv')
assert os.path.exists(gbfs_systems_csv_local_filepath)
```

The assert fails because the file does not exist in the pip installed bits.

```
$ python3
Python 3.7.2 (default, Jan 29 2019, 14:02:38)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gbfs.client import GBFSClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/gbfs/client.py", line 6, in <module>
    from gbfs.const import gbfs_client_default_language
  File "/usr/local/lib/python3.7/site-packages/gbfs/const.py", line 22, in <module>
    assert os.path.exists(gbfs_systems_csv_local_filepath)
AssertionError
>>>
```

Commenting out the assert works around the issue but is not ideal.

**Comment by jakehadar** [comment]
Thanks for the heads-up. I just tested a fix for this, and pushed the new build tagged 0.0.2 (On PyPI gbfs-client==0.0.2).
